from capstone.arm import *

EXECUTION_TIMEOUT = 30
MAX_ASM_LINES = 2048

PAGING_ENABLE = 0
PAGING_DISABLE = 1
HYPERCALL_REG = 2
TTBR0 = 3
EXIT_SVC = 4
AUTHENTICATE_SVC = 5

PAGE_MASK = 0xFFFFF000
PAGE = 0x1000
SIZE_OF_PTR = 4

PHYSICAL_MEM_SIZE = 0x800000
CODE_ADDRESS = 0x00004000
PHYSICAL_MEM_ADDR = 0
HYPERCALL_PAGE_ADDR = 0

TIME_FMT = "%Y_%m_%d_%H:%M:%S"
LEN_OF_TIME_STR = 19

STATES_FOLDER = "user_states"
INTO_FILE = '>'
ECHO = 'echo'

PAD_SIZE = KEY_SIZE = IV_SIZE = 16

STRING_HYPERCALLS = 10
